import tkinter as tk
from tkinter import Toplevel
from PIL import Image, ImageTk
import sqlite3
conn=sqlite3.connect('solar.db')
cur=conn.cursor()
cur.execute('''create table if not exists user3(planets,rateofdistance,material,moons,apparentmagnitude)''')
a=[('Murcury','1','rocky','0','-2.6'),
   ('venus','2','rocky','0','-4.9'),
   ('Earth','3','rocky','1','origin'),
   ('Mars','4','rocky','2','-2.9'),
   ('Jupiter','5','gas','95','-2.94'),
   ('Saturn','6','gas','146','-0.55'),
   ('Uranus','7','gas','27','+5.38'),
   ('Neptune','8','gas','14','+7.78')]
cur.executemany('insert into user3 values(?,?,?,?,?)',a)

def murcury_new_window():
    Mercury_window=Toplevel(root)
    Mercury_window.title('Mercury')
    Mercury_window.geometry('300x200')
    Mercury_window.configure(bg='#3b2c06')
    label=tk.Label(Mercury_window,text='Mercury:',fg='#826109',font=('times new roman',20,'bold'))
    label.pack(pady=20)
    image=Image.open(r"C:\\Users\Surface\Desktop\mercury.png")
    photo=ImageTk.PhotoImage(image)
    image_label=tk.Label(Mercury_window,image=photo)
    image_label.image=photo
    image_label.pack()
    label2=tk.Label(Mercury_window,text="Mercury is the first planet from the Sun and the smallest in the Solar System.In English, it is named after the ancient Roman god Mercurius (Mercury), god of commerce and communication,",font=('times new roman',10,'bold'),fg='#826109')
    label2.place(x=220,y=722)
    label3=tk.Label(Mercury_window,text=" and the messenger of the gods. Mercury is classified as a terrestrial planet, with roughly the same surface gravity as Mars. The surface of Mercury is heavily cratered, as a result of countless ",font=('times new roman',10,'bold'),fg='#826109')
    label3.place(x=220,y=740)
    label4=tk.Label(Mercury_window,text="  impact events that have accumulated over billions of years. Its largest crater, Caloris Planitia, has a diameter of 1,550 km (960 mi), which is about one-third the diameter of the planet (4,880 km or 3,030 mi). ",font=('times new roman',10,'bold'),fg='#826109')
    label4.place(x=220,y=758)
    label5=tk.Label(Mercury_window,text=" Similarly to the Earth's Moon, Mercury's surface displays an expansive rupes system generated from thrust faults and bright ray systems formed by impact event remnants. ",font=('times new roman',10,'bold'),fg='#826109')
    label5.place(x=220,y=776)
    exit_button=tk.Button(Mercury_window,text='Back',bg='#808000',borderwidth=5,highlightthickness=7,highlightcolor='#e674f4',command=Mercury_window.destroy,height=5,width=12)
    exit_button.place(x=100,y=700)
def venus_new_window():
    Venus_window=Toplevel(root)
    Venus_window.title('Venus')
    Venus_window.geometry('300x200')
    Venus_window.configure(bg='#3b2c06')
    label=tk.Label(Venus_window,text='Venus:',font=('times new roman',20,'bold'),fg='#826109')
    label.pack(pady=20)
    image=Image.open(r"C:\\Users\Surface\Desktop\venus.jpg")
    photo=ImageTk.PhotoImage(image)
    image_label=tk.Label(Venus_window,image=photo)
    image_label.image=photo
    image_label.pack()
    label2=tk.Label(Venus_window,text=" Venus is the second planet from the Sun. It is a terrestrial planet and is the closest in mass and size to its orbital neighbour Earth. Venus has by far the densest atmosphere of the terrestrial planets,",font=('times new roman',10,'bold'),fg='#826109')
    label2.place(x=230,y=600)
    label3=tk.Label(Venus_window,text="composed mostly of carbon dioxide with a thick, global sulfuric acid cloud cover. At the surface it has a mean temperature of 737 K (464 °C; 867 °F) and a pressure of 92 times that of Earth's at sea level.",font=('times new roman',10,'bold'),fg='#826109')
    label3.place(x=230,y=618)
    label4=tk.Label(Venus_window,text="These extreme conditions compress carbon dioxide into a supercritical state at Venus's surface.nternally, Venus has a core, mantle, and crust. Venus lacks an internal dynamo, and its weakly induced ",font=('times new roman',10,'bold'),fg='#826109')
    label4.place(x=230,y=636)
    label5=tk.Label(Venus_window,text="magnetosphere is caused by atmospheric interactions with the solar wind.",font=('times new roman',10,'bold'),fg='#826109')
    label5.place(x=230,y=654)

    exit_button=tk.Button(Venus_window,text='Back',bg='#808000',borderwidth=5,highlightthickness=7,highlightcolor='#e674f4',command=Venus_window.destroy,height=5,width=12)
    exit_button.place(x=100,y=700)
def earth_new_window():
    Earth_window=Toplevel(root)
    Earth_window.title('Earth')
    Earth_window.geometry('300x200')
    Earth_window.configure(bg='#3b2c06')
    label=tk.Label(Earth_window,text='Earth:',font=('times new roman',20,'bold'),fg='#826109')
    label.pack(pady=20)
    image=Image.open(r"C:\\Users\Surface\Desktop\earth.jpg")
    photo=ImageTk.PhotoImage(image)
    image_label=tk.Label(Earth_window,image=photo)
    image_label.image=photo
    image_label.pack()
    label2=tk.Label(Earth_window,text=" Earth is the third planet from the Sun and the only astronomical object known to harbor life. This is enabled by Earth being an ocean world, the only one in the Solar System sustaining liquid surface water.",font=('times new roman',10,'bold'),fg='#826109')
    label2.place(x=220,y=750)
    label3=tk.Label(Earth_window,text="Almost all of Earth's water is contained in its global ocean, covering 70.8% of Earth's crust. The remaining 29.2% of Earth's crust is land, most of which is located in the form of continental landmasses within ",font=('times new roman',10,'bold'),fg='#826109')
    label3.place(x=220,y=768)
    label4=tk.Label(Earth_window,text="Earth's land hemisphere. Most of Earth's land is somewhat humid and covered by vegetation, while large sheets of ice at Earth's polar deserts retain more water than Earth's groundwater, lakes, rivers and",font=('times new roman',10,'bold'),fg='#826109')
    label4.place(x=220,y=786)
    label5=tk.Label(Earth_window,text="atmospheric water combined. Earth's crust consists of slowly moving tectonic plates, which interact to produce mountain ranges, volcanoes, and earthquakes.",font=('times new roman',10,'bold'),fg='#826109')
    label5.place(x=220,y=804)
    exit_button=tk.Button(Earth_window,text='Back',bg='#808000',borderwidth=5,highlightthickness=7,highlightcolor='#e674f4',command=Earth_window.destroy,height=5,width=12)
    exit_button.place(x=100,y=650)
def mars_new_window():
    Mars_window=Toplevel(root)
    Mars_window.title('Mars')
    Mars_window.geometry('300x200')
    Mars_window.configure(bg='#3b2c06')
    label=tk.Label(Mars_window,text='Mars:',font=('times new roman',20,'bold'),fg='#826109')
    label.pack(pady=20)
    image=Image.open(r"C:\\Users\Surface\Desktop\mars5.png")
    photo=ImageTk.PhotoImage(image)
    image_label=tk.Label(Mars_window,image=photo)
    image_label.image=photo
    image_label.pack()
    label2=tk.Label(Mars_window,text=" Mars is the fourth planet from the Sun. The surface of Mars is orange-red because it is covered in iron(III) oxide dust, giving it the nickname 'the Red Planet'. Mars is among the brightest objects in",font=('times new roman',10,'bold'),fg='#826109')
    label2.place(x=230,y=680)
    label3=tk.Label(Mars_window,text="Earth's sky, and its high-contrast albedo features have made it a common subject for telescope viewing. It is classified as a terrestrial planet and is the second smallest of the Solar System's planets with",font=('times new roman',10,'bold'),fg='#826109')
    label3.place(x=230,y=698)
    label4=tk.Label(Mars_window,text="a diameter of 6,779 km (4,212 mi). In terms of orbital motion, a Martian solar day (sol) is equal to 24.5 hours, and a Martian solar year is equal to 1.88 Earth years (687 Earth days). Mars has two natural",font=('times new roman',10,'bold'),fg='#826109')
    label4.place(x=230,y=716)
    label5=tk.Label(Mars_window,text="satellites that are small and irregular in shape: Phobos and Deimos.",font=('times new roman',10,'bold'),fg='#826109')
    label5.place(x=230,y=734)
    exit_button=tk.Button(Mars_window,text='Back',bg='#808000',borderwidth=5,highlightthickness=7,highlightcolor='#e674f4',command=Mars_window.destroy,height=5,width=12)
    exit_button.place(x=100,y=700)
def jupiter_new_window():
    Jupiter_window=Toplevel(root)
    Jupiter_window.title('Jupiter')
    Jupiter_window.geometry('300x200')
    Jupiter_window.configure(bg='#3b2c06')
    label=tk.Label(Jupiter_window,text='Jupiter:',font=('times new roman',20,'bold'),fg='#826109')
    label.pack(pady=20)
    image=Image.open(r"C:\\Users\Surface\Desktop\jupiter.jpg")
    photo=ImageTk.PhotoImage(image)
    image_label=tk.Label(Jupiter_window,image=photo)
    image_label.image=photo
    image_label.pack()
    label2=tk.Label(Jupiter_window,text="Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass more than 2.5 times that of all the other planets in the Solar System combined ",font=('times new roman',10,'bold'),fg='#826109')
    label2.place(x=230,y=630)
    label3=tk.Label(Jupiter_window,text="and slightly less than one-thousandth the mass of the Sun. Its diameter is eleven times that of Earth, and a tenth that of the Sun. Jupiter orbits the Sun at a distance of 5.20 AU (778.5 Gm), ",font=('times new roman',10,'bold'),fg='#826109')
    label3.place(x=230,y=648)
    label4=tk.Label(Jupiter_window,text="with an orbital period of 11.86 years. It is the third brightest natural object in the Earth's night sky, after the Moon and Venus, and has been observed since prehistoric times. Its name derives",font=('times new roman',10,'bold'),fg='#826109')
    label4.place(x=230,y=666)
    label5=tk.Label(Jupiter_window,text="from that of Jupiter, the chief deity of ancient Roman religion. ",font=('times new roman',10,'bold'),fg='#826109')
    label5.place(x=230,y=684)
    exit_button=tk.Button(Jupiter_window,text='Back',bg='#808000',borderwidth=5,highlightthickness=7,highlightcolor='#e674f4',command=Jupiter_window.destroy,height=5,width=12)
    exit_button.place(x=100,y=700)

def saturn_new_window():
    Saturn_window=Toplevel(root)
    Saturn_window.title('Saturn')
    Saturn_window.geometry('300x200')
    Saturn_window.configure(bg='#3b2c06')

    label=tk.Label(Saturn_window,text='Saturn:',font=('times new roman',20,'bold'),fg='#826109')
    label.pack(pady=20)
    image=Image.open(r"C:\\Users\Surface\Desktop\saturn.png")
    photo=ImageTk.PhotoImage(image)
    image_label=tk.Label(Saturn_window,image=photo)
    image_label.image=photo
    image_label.pack()
    label2=tk.Label(Saturn_window,text=" Saturn is the sixth planet from the Sun and the second largest in the Solar System, after Jupiter. It is a gas giant, with an average radius of about nine times that of Earth.It has",font=('times new roman',10,'bold'),fg='#826109')
    label2.place(x=230,y=650)
    label2=tk.Label(Saturn_window,text="an eighth the average density of Earth, but is over 95 times more massive.Even though Saturn is almost as big as Jupiter, Saturn has less than a third the mass of Jupiter.",font=('times new roman',10,'bold'),fg='#826109')
    label2.place(x=230,y=668)
    label3=tk.Label(Saturn_window,text="Saturn orbits the Sun at a distance of 9.59 AU (1,434 million km), with an orbital period of 29.45 years",font=('times new roman',10,'bold'),fg='#826109')
    label3.place(x=230,y=686)
    exit_button=tk.Button(Saturn_window,text='Back',bg='#808000',borderwidth=5,highlightthickness=7,highlightcolor='#e674f4',command=Saturn_window.destroy,height=5,width=12)
    exit_button.place(x=60,y=700)
  
def uranus_new_window():
    Uranus_window=Toplevel(root)
    Uranus_window.title('Uranus')
    Uranus_window.geometry('300x200')
    Uranus_window.configure(bg='#3b2c06')
    label=tk.Label(Uranus_window,text='Uranus:',font=('times new roman',20,'bold'),fg='#826109')
    label.pack(pady=20)
    image=Image.open(r"C:\\Users\Surface\Desktop\uranus.jpg")
    photo=ImageTk.PhotoImage(image)
    image_label=tk.Label(Uranus_window,image=photo)
    image_label.image=photo
    image_label.pack()
    label2=tk.Label(Uranus_window,text=" Uranus is the seventh planet from the Sun. It is a gaseous cyan-coloured ice giant. Most of the planet is made of water, ammonia, and methane in a supercritical phase of matter, which astronomy",font=('times new roman',10,'bold'),fg='#826109')
    label2.place(x=230,y=550)
    label3=tk.Label(Uranus_window,text="calls 'ice' or volatiles. The planet's atmosphere has a complex layered cloud structure and has the lowest minimum temperature (49 K (−224 °C; −371 °F)) of all the Solar System's planets.",font=('times new roman',10,'bold'),fg='#826109')
    label3.place(x=230,y=568)
    label4=tk.Label(Uranus_window,text="It has a marked axial tilt of 82.23° with a retrograde rotation period of 17 hours and 14 minutes. This means that in an 84-Earth-year orbital period around the Sun, its poles get around 42 years",font=('times new roman',10,'bold'),fg='#826109')
    label4.place(x=230,y=586)
    label5=tk.Label(Uranus_window,text="of continuous sunlight, followed by 42 years of continuous darkness.",font=('times new roman',10,'bold'),fg='#826109')
    label5.place(x=230,y=604)
    exit_button=tk.Button(Uranus_window,text='Back',bg='#808000',borderwidth=5,highlightthickness=7,highlightcolor='#e674f4',command=Uranus_window.destroy,height=5,width=12)
    exit_button.place(x=100,y=700)
def neptune_new_window():
    Neptune_window=Toplevel(root)
    Neptune_window.title('Neptune')
    Neptune_window.geometry('300x200')
    Neptune_window.configure(bg='#3b2c06')
    label=tk.Label(Neptune_window,text='Neptune:',font=('times new roman',20,'bold'),fg='#826109')
    label.pack(pady=20)
    image=Image.open(r"C:\\Users\Surface\Desktop\neptune.png")
    photo=ImageTk.PhotoImage(image)
    image_label=tk.Label(Neptune_window,image=photo)
    image_label.image=photo
    image_label.pack()
    label2=tk.Label(Neptune_window,text="Neptune is the eighth and farthest known planet from the Sun. It is the fourth-largest planet in the Solar System by diameter, the third-most-massive planet, and the densest giant planet.",font=('times new roman',10,'bold'),fg='#826109')
    label2.place(x=230,y=650)
    label3=tk.Label(Neptune_window,text="It is 17 times the mass of Earth and slightly more massive, but denser and smaller, than fellow ice giant Uranus. Being composed primarily of gases and liquids,it has no well-defined solid surface,",font=('times new roman',10,'bold'),fg='#826109')
    label3.place(x=230,y=668)
    label4=tk.Label(Neptune_window,text="and orbits the Sun once every 164.8 years at an orbital distance of 30.1 astronomical units (4.5 billion kilometres; 2.8 billion miles). It is named after the Roman god of the sea and has the astronomical.",font=('times new roman',10,'bold'),fg='#826109')
    label4.place(x=230,y=686)
    label5=tk.Label(Neptune_window,text="symbol ♆, representing Neptune's trident.",font=('times new roman',10,'bold'),fg='#826109')
    label5.place(x=230,y=704)
    exit_button=tk.Button(Neptune_window,text='Back',bg='#808000',borderwidth=5,highlightthickness=7,highlightcolor='#e674f4',command=Neptune_window.destroy,height=5,width=12)
    exit_button.place(x=100,y=700)
  


root=tk.Tk()
root.title('Solar System')
root.geometry('400x300')
root.configure(bg='#0d6d9d')

label1=tk.Label(root,text='Solar System',font=('times new roman',40,'bold'),fg='#330674')
label1.place(x= 500,y=50)
label2=tk.Label(root,text='Press the buttoms and give information about each planet in solar system:',font=('times new roman',20,'bold'),fg='#330674',bg='silver')
label2.place(x= 230,y=150)
mercury_button=tk.Button(root,text='Mercury Planet',font=('times new roman',20,'bold'),fg='#c0c0c0',bg='#663399',borderwidth=5,highlightthickness=7,highlightcolor='#e674f4',width=15,height=3,command=lambda:murcury_new_window())
mercury_button.place(x=100,y=230)
venus_button=tk.Button(root,text='Venus Planet',font=('times new roman',20,'bold'),fg='#c0c0c0',bg='#663399',borderwidth=5,highlightthickness=7,highlightcolor='#e674f4',width=15,height=3,command=lambda:venus_new_window())
venus_button.place(x=450,y=230)
earth_button=tk.Button(root,text='Earth Planet',font=('times new roman',20,'bold'),fg='#c0c0c0',bg='#663399',borderwidth=5,highlightthickness=7,highlightcolor='#e674f4',width=15,height=3,command=lambda:earth_new_window())
earth_button.place(x=800,y=230)
mars_button=tk.Button(root,text='Mars Planet',font=('times new roman',20,'bold'),fg='#c0c0c0',bg='#663399',borderwidth=5,highlightthickness=7,highlightcolor='#e674f4',width=15,height=3,command=lambda:mars_new_window())
mars_button.place(x=100,y=435)
jupiter_button=tk.Button(root,text='Jupiter Planet',font=('times new roman',20,'bold'),fg='#c0c0c0',bg='#663399',borderwidth=5,highlightthickness=7,highlightcolor='#e674f4',width=15,height=3,command=lambda:jupiter_new_window())
jupiter_button.place(x=450,y=435)
saturn_button=tk.Button(root,text='Saturn Planet',font=('times new roman',20,'bold'),fg='#c0c0c0',bg='#663399',borderwidth=5,highlightthickness=7,highlightcolor='#e674f4',width=15,height=3,command=lambda:saturn_new_window())
saturn_button.place(x=800,y=435)
uranus_button=tk.Button(root,text='Uranus Planet',font=('times new roman',20,'bold'),fg='#c0c0c0',bg='#663399',borderwidth=5,highlightthickness=7,highlightcolor='#e674f4',width=15,height=3,command=lambda:uranus_new_window())
uranus_button.place(x=450,y=650)
neptune_button=tk.Button(root,text='Neptune Planet',font=('times new roman',20,'bold'),fg='#c0c0c0',bg='#663399',borderwidth=5,highlightthickness=7,highlightcolor='#e674f4',width=15,height=3,command=lambda:neptune_new_window())
neptune_button.place(x=800,y=650)


exit_button=tk.Button(root,text='Close',font=('times new roman',12,'bold'),bg='#826109',borderwidth=5,highlightthickness=7,highlightcolor='#e674f4',command=root.quit,height=5,width=12)
exit_button.place(x=100,y=650)





conn.commit()
conn.close()
root.mainloop()